# Generated by Django 3.1.4 on 2021-01-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('firsthalf', models.IntegerField(max_length=1)),
                ('secondhalf', models.ManyToManyField(to='analysis.Allergies')),
            ],
            options={
                'db_table': 'components',
            },
        ),
    ]
