# Generated by Django 3.1.4 on 2021-01-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='allergies',
            field=models.ManyToManyField(to='analysis.Allergies'),
        ),
        migrations.RemoveField(
            model_name='components',
            name='secondhalf',
        ),
        migrations.AddField(
            model_name='components',
            name='secondhalf',
            field=models.IntegerField(default=None, max_length=1),
            preserve_default=False,
        ),
    ]
