# Generated by Django 3.1.4 on 2021-01-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210104_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=50)),
                ('percentage', models.FloatField()),
                ('influences', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'analysis',
            },
        ),
        migrations.AlterField(
            model_name='components',
            name='firsthalf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='components',
            name='secondhalf',
            field=models.IntegerField(),
        ),
    ]
